### PR TITLE
Removed bower and switched to usemin

### LINKED ISSUE #14: Depreciate bower and switch to usemin
I don't like bower, so we're not going to use it. We're going to switch all the modules we need into package.json. We're also going to switch to usemin so we can install packages much more easily

### PR DESCRIPTION
**Pull request by madhavgharmalkar**
Closes #14

### CODE REVIEW

**Review by chriswongtv — APPROVED** [review]
lgtm

**Review by chriswongtv — CHANGES_REQUESTED** [review]
Could you update the setup instructions on README to reflect this change?

**Comment by madhavgharmalkar** [comment]
@chriswongtv changes have been made, please review them 🙏

**Review by chriswongtv — APPROVED** [review]

**Comment by chriswongtv** [comment]
@madhavgharmalkar thanks for updating 😃 🚀

**Pull request merged**
